spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/final-project
    username: postgres
    password: amir1124
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
